apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: little-clam-go
  janus-idp.io/tekton: little-clam-go
  backstage.io/kubernetes-id: little-clam-go
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: little-clam-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
