apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: little-clam-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: little-clam-go 
  name: little-clam-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: little-clam-go 
